-- ============================================================
-- plan_pm – pełny schemat bazy danych (zgodny z produkcją)
-- Wklej w Supabase SQL Editor i uruchom
-- UWAGA: GENERATED BY DEFAULT (zamiast ALWAYS) pozwala na sync danych z prod
-- ============================================================

-- ── Infrastruktura ──────────────────────────────────────────

create table building (
  id   uuid not null default gen_random_uuid(),
  name varchar not null unique,
  constraint building_pkey primary key (id)
);

create table rooms (
  id       uuid not null default gen_random_uuid(),
  name     varchar not null,
  building uuid,
  constraint rooms_pkey primary key (id),
  constraint rooms_building_fkey foreign key (building) references public.building (id)
);

create table teachers (
  id         uuid    not null default gen_random_uuid(),
  "fullName" text    not null,
  title      varchar not null,
  constraint teachers_pkey primary key (id)
);

-- ── Struktura uczelni ────────────────────────────────────────

create table faculties (
  id   bigint not null generated by default as identity,
  name varchar not null unique,
  constraint faculties_pkey primary key (id)
);

create table degree_courses (
  id         bigint  not null generated by default as identity,
  name       varchar not null unique,
  faculty_id bigint,
  constraint degree_courses_pkey primary key (id),
  constraint degree_courses_faculty_id_fkey foreign key (faculty_id) references public.faculties (id)
);

create table specialisations (
  id               bigint  not null generated by default as identity,
  name             varchar not null unique,
  degree_course_id bigint,
  constraint specialisations_pkey primary key (id),
  constraint specialisations_degree_course_i_fkey foreign key (degree_course_id) references public.degree_courses (id)
);

-- ── Programy ─────────────────────────────────────────────────

create table programs (
  id             uuid    not null default gen_random_uuid(),
  name           varchar not null,
  "programType"  varchar not null,
  "degreeLevel"  varchar not null,
  language       varchar not null,
  "academicYear" varchar not null,
  "courseLength" real    not null,
  year           smallint,
  constraint programs_pkey primary key (id)
);

create table program_faculties (
  id         uuid   not null default gen_random_uuid(),
  program_id uuid   not null unique,
  faculty_id bigint not null,
  created_at timestamptz not null default now(),
  constraint program_faculties_pkey primary key (id),
  constraint program_faculties_program_id_fkey foreign key (program_id) references public.programs (id),
  constraint program_faculties_faculty_id_fkey foreign key (faculty_id) references public.faculties (id)
);

-- ── Zajęcia ──────────────────────────────────────────────────

create table classes (
  id          uuid    not null default gen_random_uuid(),
  subject     varchar not null,
  "group"     varchar not null,
  program     uuid,
  room        uuid,
  "startTime" timestamp without time zone,
  "endTime"   timestamp without time zone,
  notes       text,
  constraint classes_pkey primary key (id),
  constraint classes_program_fkey foreign key (program) references public.programs (id),
  constraint classes_room_fkey    foreign key (room)    references public.rooms (id)
);

create table teachersclasses (
  id       uuid not null default gen_random_uuid(),
  teachers uuid not null,
  classes  uuid not null,
  constraint teachersclasses_pkey primary key (id),
  constraint teachersclasses_teachers_fkey foreign key (teachers) references public.teachers (id),
  constraint teachersclasses_classes_fkey  foreign key (classes)  references public.classes (id)
);

-- ── Aktualności ──────────────────────────────────────────────

create table news (
  id           uuid    not null default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  title        varchar not null,
  content      text    not null,
  message_type varchar not null,
  constraint news_pkey primary key (id)
);

-- ── Użytkownicy admin ────────────────────────────────────────
-- UWAGA: W produkcji admin_users.id FK → auth.users(id).
-- W bazie testowej pomijamy tę FK bo auth.users nie są syncowane.

create table admin_users (
  id             uuid not null default gen_random_uuid(),
  email          text not null unique,
  first_name     text not null,
  last_name      text not null,
  role           text not null check (role = any (array['administrator','rektorat','dziekanat','prowadzacy'])),
  position       text,
  academic_title text,
  faculty_id     bigint,
  teacher_id     uuid,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint admin_users_pkey primary key (id),
  constraint admin_users_faculty_id_fkey foreign key (faculty_id) references public.faculties (id),
  constraint admin_users_teacher_id_fkey foreign key (teacher_id) references public.teachers (id)
);

-- ── Koła naukowe ─────────────────────────────────────────────

create table student_clubs (
  id          uuid not null default gen_random_uuid(),
  name        text not null,
  description text,
  leader_id   uuid,
  faculty_id  bigint,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint student_clubs_pkey primary key (id),
  constraint student_clubs_leader_id_fkey foreign key (leader_id) references public.admin_users (id),
  constraint student_clubs_faculty_id_fkey foreign key (faculty_id) references public.faculties (id)
);

-- ── Przypisania nauczycieli ──────────────────────────────────

create table teacher_assignments (
  id            uuid not null default gen_random_uuid(),
  admin_user_id uuid not null,
  program_id    uuid,
  subject_name  text,
  group_name    text,
  created_at    timestamptz not null default now(),
  constraint teacher_assignments_pkey primary key (id),
  constraint teacher_assignments_admin_user_id_fkey foreign key (admin_user_id) references public.admin_users (id),
  constraint teacher_assignments_program_id_fkey    foreign key (program_id)    references public.programs (id)
);

-- ── Wydarzenia ───────────────────────────────────────────────

create table schedule_events (
  id          uuid not null default gen_random_uuid(),
  title       text not null,
  description text,
  start_time  timestamp without time zone not null,
  end_time    timestamp without time zone not null,
  room_id     uuid,
  club_id     uuid,
  faculty_id  bigint,
  program_id  uuid,
  created_by  uuid not null,
  is_visible  boolean not null default true,
  created_at  timestamptz not null default now(),
  constraint schedule_events_pkey primary key (id),
  constraint schedule_events_created_by_fkey  foreign key (created_by)  references public.admin_users (id),
  constraint schedule_events_room_id_fkey     foreign key (room_id)     references public.rooms (id),
  constraint schedule_events_club_id_fkey     foreign key (club_id)     references public.student_clubs (id),
  constraint schedule_events_faculty_id_fkey  foreign key (faculty_id)  references public.faculties (id),
  constraint schedule_events_program_id_fkey  foreign key (program_id)  references public.programs (id)
);

-- ── Odwołania i przekładanie zajęć ───────────────────────────

create table class_cancellations (
  id           uuid not null default gen_random_uuid(),
  class_id     uuid not null unique,
  reason       text,
  cancelled_by uuid not null,
  created_at   timestamptz not null default now(),
  constraint class_cancellations_pkey primary key (id),
  constraint class_cancellations_class_id_fkey     foreign key (class_id)     references public.classes (id),
  constraint class_cancellations_cancelled_by_fkey foreign key (cancelled_by) references public.admin_users (id)
);

create table class_reschedules (
  id             uuid not null default gen_random_uuid(),
  class_id       uuid not null unique,
  new_start_time timestamp without time zone not null,
  new_end_time   timestamp without time zone not null,
  new_room_id    uuid,
  reason         text,
  rescheduled_by uuid not null,
  created_at     timestamptz not null default now(),
  constraint class_reschedules_pkey primary key (id),
  constraint class_reschedules_class_id_fkey      foreign key (class_id)       references public.classes (id),
  constraint class_reschedules_new_room_id_fkey   foreign key (new_room_id)    references public.rooms (id),
  constraint class_reschedules_rescheduled_by_fkey foreign key (rescheduled_by) references public.admin_users (id)
);

-- ── Godziny rektorskie ───────────────────────────────────────

create table rector_hours (
  id          uuid not null default gen_random_uuid(),
  date        date not null,
  start_time  time without time zone,
  end_time    time without time zone,
  is_full_day boolean not null default false,
  description text,
  created_by  uuid not null,
  created_at  timestamptz not null default now(),
  constraint rector_hours_pkey primary key (id),
  constraint rector_hours_created_by_fkey foreign key (created_by) references public.admin_users (id)
);
