-- ============================================================
-- plan_pm – schemat bazy danych
-- GENERATED BY DEFAULT (zamiast ALWAYS) pozwala na sync danych z prod
-- ============================================================

create table public.building (
  id   uuid not null default gen_random_uuid(),
  name character varying not null unique,
  constraint building_pkey primary key (id)
);

create table public.rooms (
  id       uuid not null default gen_random_uuid(),
  name     character varying not null,
  building uuid,
  constraint rooms_pkey primary key (id),
  constraint rooms_building_fkey foreign key (building) references public.building (id),
  constraint rooms_name_building_key unique (name, building)
);

create table public.teachers (
  id         uuid not null default gen_random_uuid(),
  "fullName" text not null,
  title      character varying not null,
  constraint teachers_pkey primary key (id),
  constraint teachers_fullname_title_key unique ("fullName", title)
);

create table public.faculties (
  id   bigint not null generated by default as identity,
  name character varying not null unique,
  constraint faculties_pkey primary key (id)
);

create table public.degree_courses (
  id         bigint not null generated by default as identity,
  name       character varying not null unique,
  faculty_id bigint,
  constraint degree_courses_pkey primary key (id),
  constraint degree_courses_faculty_id_fkey foreign key (faculty_id) references public.faculties (id)
);

create table public.specialisations (
  id               bigint not null generated by default as identity,
  name             character varying not null unique,
  degree_course_id bigint,
  constraint specialisations_pkey primary key (id),
  constraint specialisations_degree_course_i_fkey foreign key (degree_course_id) references public.degree_courses (id)
);

create table public.programs (
  id              uuid not null default gen_random_uuid(),
  name            character varying not null,
  "programType"   character varying not null,
  "degreeLevel"   character varying not null,
  language        character varying not null,
  "academicYear"  character varying not null,
  "courseLength"  real not null,
  year            smallint,
  constraint programs_pkey primary key (id),
  constraint programs_name_type_level_lang_year_key unique (name, "programType", "degreeLevel", language, "academicYear")
);

create table public.classes (
  id          uuid not null default gen_random_uuid(),
  subject     character varying not null,
  "group"     character varying not null,
  program     uuid,
  room        uuid,
  "startTime" timestamp without time zone,
  "endTime"   timestamp without time zone,
  notes       text,
  constraint classes_pkey primary key (id),
  constraint classes_program_fkey foreign key (program) references public.programs (id),
  constraint classes_room_fkey    foreign key (room)    references public.rooms (id),
  constraint classes_subject_start_group_program_key unique (subject, "startTime", "group", program)
);

create table public.teachersclasses (
  id       uuid not null default gen_random_uuid(),
  teachers uuid not null,
  classes  uuid not null,
  constraint teachersclasses_pkey primary key (id),
  constraint teachersclasses_teachers_fkey foreign key (teachers) references public.teachers (id),
  constraint teachersclasses_classes_fkey  foreign key (classes)  references public.classes (id),
  constraint teachersclasses_teachers_classes_key unique (teachers, classes)
);

create table public.news (
  id           uuid not null default gen_random_uuid(),
  created_at   timestamp with time zone not null default now(),
  title        character varying not null,
  content      text not null,
  message_type character varying not null,
  image_url    text,
  constraint news_pkey primary key (id)
);

create table public.app_announcements (
  id         uuid not null default gen_random_uuid(),
  created_at timestamp with time zone default now(),
  title      text not null,
  message    text not null,
  type       text not null check (type = any (array['info'::text, 'warning'::text, 'update'::text])),
  active     boolean not null default true,
  store_url  text,
  constraint app_announcements_pkey primary key (id)
);
